sudo: required

dist: xenial

language: python

python: 3.7

services: docker

script:
  - make build

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  file: 
    - tmux_xenial
    - tmux_bionic
  skip_cleanup: true
  on:
    tags: true
